services:

  api-server:
    networks:
      - starlinknet
  
  scheduler:
    networks:
      - starlinknet
  
  triggerer:
    networks:
      - starlinknet

  minio:
    image: quay.io/minio/minio:RELEASE.2025-07-23T15-54-02Z
    container_name: datalake
    hostname: minio
    restart: always
    volumes:
      - ./include/data/minio:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - starlinknet
  
  warehouse:
    image: postgres:15
    container_name: warehouse
    hostname: warehouse
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=spacex
      - POSTGRES_USER=warehouse
      - POSTGRES_PASSWORD=warehouse123
    networks:
      - starlinknet
  
networks:
  starlinknet:
    driver: bridge
